version: '3.7'
services:
  ####################################################################################################
  # The Application
  ####################################################################################################
  app:
    container_name: app
    build:
      context: .
      dockerfile: "docker/php/Dockerfile.dev"
      args:
        - TAG=${BACKEND_TAG}
    expose:
      - ${BACKEND_CONTAINER_PORT}
    environment:
      - COMPOSER=${BACKEND_ENV_COMPOSER}
      - PHP_EXTENSION_XDEBUG=1
    volumes:
      - ./source:/var/www
    working_dir: /var/www
    networks:
      - net_webserver

  ####################################################################################################
  # The Web Server
  ####################################################################################################
  nginx_app:
    container_name: nginx_app
    build:
      context: .
      dockerfile: "docker/nginx/Dockerfile"
      args:
        - TAG=${WEBSERVER_TAG}
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "${WEBSERVER_HOST_PORT}:${WEBSERVER_CONTAINER_PORT}"
    working_dir: /etc/nginx/conf.d/
    networks:
      - net_webserver
    depends_on:
      - app

networks:
  net_webserver: {}